version: '3'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=call_log
      - MONGO_INITDB_ROOT_USERNAME=testAdmin
      - MONGO_INITDB_ROOT_PASSWORD=somePassword
    ports:
      - 27017:27017
#  api:
#    image: call-log/backend
#    ports:
#      - 8080:8080