server:
  http2.enabled: true
  compression:
    enabled: true
    min-response-size: 1024
spring:
  data:
    mongodb:
      username: testAdmin
      password: somePassword
      database: call_log
      port: 27017
      host: localhost